### ISSUE TITLE
scipy DLL hell. ImportError: DLL load failed

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#18]
En testant le fichier [TestLibrairies](https://github.com/cspaier/pydiderot/blob/dev/Thonny/Lib/site-packages/TestLibrairies.py) sous windows 7, j'ai l'érreur suivante:

```Traceback (most recent call last):
  File "C:\Users\cspaier\python\test.py", line 1, in <module>
    import TestLibrairies.py
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\thonny\backend.py", line 317, in _custom_import
    module = self._original_import(*args, **kw)
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\TestLibrairies.py", line 9, in <module>
    from lycee import *
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\thonny\backend.py", line 317, in _custom_import
    module = self._original_import(*args, **kw)
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\lycee.py", line 27, in <module>
    from stats_proba import *
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\thonny\backend.py", line 317, in _custom_import
    module = self._original_import(*args, **kw)
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\stats_proba.py", line 13, in <module>
    from scipy.stats import norm
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\thonny\backend.py", line 317, in _custom_import
    module = self._original_import(*args, **kw)
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\scipy\stats\__init__.py", line 367, in <module>
    from .stats import *
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\thonny\backend.py", line 317, in _custom_import
    module = self._original_import(*args, **kw)
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\scipy\stats\stats.py", line 172, in <module>
    import scipy.special as special
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\thonny\backend.py", line 317, in _custom_import
    module = self._original_import(*args, **kw)
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\scipy\special\__init__.py", line 641, in <module>
    from ._ufuncs import *
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\thonny\backend.py", line 317, in _custom_import
    module = self._original_import(*args, **kw)
  File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
  File "C:\Users\cspaier\Downloads\pydiderot-dev\Thonny\lib\site-packages\thonny\backend.py", line 317, in _custom_import
    module = self._original_import(*args, **kw)
ImportError: DLL load failed: Le module spécifié est introuvable.
```

En gros, notre fichier [stats_proba](https://github.com/cspaier/pydiderot/blob/f3c6b547d2b93fd688341c0f720589e4fc5df669/Thonny/Lib/site-packages/stats_proba.py#L13) lance `from scipy.stats import norm` qui à sont tour lance `import scipy.special as special`. Ce dernier provoque ` ImportError: DLL load failed: Le module spécifié est introuvable`.

Des utilisateurs de conda on [le même problème](https://github.com/conda/conda/issues/6396) mais nous n' utilisons pas [conda](https://conda.io/docs/) à ma connaissance. J'ai testé plusieurs manière d'installer scipy en vain.

Je propose de mettre en quarantaine la librairie `stats_proba` jusqu'a ce qu'on résolve cela. En gros, on indique que ca fonctionne pas dans la doc en liant vers cette issue et on retire les tests de `TestLibrairies.py`

Je ne crois pas que l'on ai tésté `stats_proba` sous windows en fait donc il est très probable que ce problème ait été présent depuis le début.

**Comment by al-coloic** [comment]
En plus la plupart des fonctions opérant sur des listes de données font appel à une fonction "compte" qui est absente.

Comme d'hab c'est les stats qui font ch...

**Comment by cspaier** [comment]
Résolu! Le commit arrive.
![image](https://user-images.githubusercontent.com/44053087/50739006-2bfc2b80-11da-11e9-8d71-db5242e6592d.png)

**Comment by cspaier** [comment]
C'est un problème apparemment commun nommé "DLL hell".

Résolu en installant les paquets à partir de  [ce dépot](https://www.lfd.uci.edu/~gohlke/pythonlibs/).

**Comment by cspaier** [comment]
Mauvaise nouvelle:

Ca fonctionne en B318 mais pas en salle des profs de math. Il faut que je teste sous pleins de windows différents à la maison j'imagine. On peut pas raisonnablement se passer de scipy?

**Comment by cspaier** [comment]
Le bug n'est plus présent depuis qu'on a supprimé numpy.
